-- MySQL Script generated by MySQL Workbench
-- Fri Oct  1 23:44:07 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema testphp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema testphp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `testphp` DEFAULT CHARACTER SET utf8 ;
USE `testphp` ;

-- -----------------------------------------------------
-- Table `testphp`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testphp`.`rol` (
  `idrol` INT NOT NULL AUTO_INCREMENT,
  `rol` VARCHAR(45) NULL,
  `descripcion` VARCHAR(60) NULL,
  PRIMARY KEY (`idrol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testphp`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testphp`.`persona` (
  `idpersona` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NULL,
  `apellidos` VARCHAR(120) NULL,
  `correo` VARCHAR(120) NULL,
  `password` VARCHAR(250) NULL,
  `idrol` INT NOT NULL,
  PRIMARY KEY (`idpersona`),
  INDEX `fk_personas_roles_idx` (`idrol` ASC) VISIBLE,
  CONSTRAINT `fk_personas_roles`
    FOREIGN KEY (`idrol`)
    REFERENCES `testphp`.`rol` (`idrol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testphp`.`publicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testphp`.`publicacion` (
  `idpublicacion` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NULL,
  `descripcion` VARCHAR(450) NULL,
  PRIMARY KEY (`idpublicacion`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `testphp`.`rol`
-- -----------------------------------------------------
START TRANSACTION;
USE `testphp`;
INSERT INTO `testphp`.`rol` (`idrol`, `rol`, `descripcion`) VALUES (1, 'Rol Basico', 'permiso de acceso');
INSERT INTO `testphp`.`rol` (`idrol`, `rol`, `descripcion`) VALUES (2, 'Rol Medio', 'permiso de acceso y consulta');
INSERT INTO `testphp`.`rol` (`idrol`, `rol`, `descripcion`) VALUES (3, 'Rol Medio Alto', 'permiso de acceso y agregar');
INSERT INTO `testphp`.`rol` (`idrol`, `rol`, `descripcion`) VALUES (4, 'Rol Alto Medio', 'permiso de acceso, consulta, agregar y actualizar');
INSERT INTO `testphp`.`rol` (`idrol`, `rol`, `descripcion`) VALUES (5, 'Rol Alto', 'permiso de acceso, consulta, agregar, actualizar y eliminar');

COMMIT;

